config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations" }

  get "dashboards/index", to: "dashboards#index", as: "dashboard"
  
  resources :subscribes, only: [:create]
  resources :adverts do 
    resources :comments, only: [:create]
  end

  root 'adverts#index', to:'advert#index'
end

app/models/advert.rb
class Advert < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
  belongs_to :settlement
	has_many :comments

	accepts_nested_attributes_for :comments
  serialize :payment_methods, Array

	PAYMENT = [
             {id: 1, name: "CASH"},
             {id: 2,name: "CARD"}
            ]
  MAX_DESCRIPTION_CHARACTERS = 200

  validates :title, presence: true
  validates :description, presence: true, length: 1..MAX_DESCRIPTION_CHARACTERS
  validates :address, presence: true
  validates :location, presence: true

  class << self
  	#TODO Potrebno je da se automatski prebauje na inactive ako je oglas aktivan vise od 30 dana
    def active 
      where(:active => true)
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :adverts

	validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :advert
  before_save :set_owner


  private
  def set_owner
    if owner.blank?
      self.owner = "Anoniman korisnik"
    end
    # self.owner ||= "Anoniman korinsik"
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/settlement.rb
class Settlement < ActiveRecord::Base
	has_many :subscribes
	has_many :adverts

end

app/models/subscribe.rb
class Subscribe < ActiveRecord::Base
	belongs_to :settlement

	validates :email, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :adverts
	mount_uploader :image, ImageUploader
	
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	
  validates :user_name, presence: true, uniqueness: true, length: 4..20
   
end
 	

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :set_advert, only: [:show, :edit, :update, :destroy]

  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = Advert.active
    @settlements = Settlement.all
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
    @comments = @advert.comments
  end

  # GET /adverts/new
  def new
    @advert = Advert.new
  end

  # GET /adverts/1/edit
  def edit
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = Advert.new(advert_params)
    @advert.user = current_user
    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render action: 'show', status: :created, location: @advert }
      else
        format.html { render action: 'new' }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adverts/1
  # PATCH/PUT /adverts/1.json
  def update
    respond_to do |format|
      if @advert.update(advert_params)
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert.destroy
    respond_to do |format|
      format.html { redirect_to adverts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advert
      @advert = Advert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advert_params
      params[:advert].permit(:title, :description, :address, :location, :phone_number, :commentable, :payment_method, :category_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password, :password_confirmation, :image ) }
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:user_name, :email, :first_name, :last_name, :mobile_number_1, :mobile_number_2, :image)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
		@advert = Advert.find(params[:advert_id])
		@advert.comments.create(comment_params)
		redirect_to @advert	
	end

	private
	def comment_params
		params[:comment].permit(:owner, :content)
	end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!  
  
  def index
  	@all_my_adverts = current_user.adverts
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def update
		@user = User.find(current_user.id)
		params[:user].delete(:current_password)
		if current_user.update_attributes(user_params)
			redirect_to dashboard_path, notice: "Successfully updated"
		else
			redirect_to dashboard_path, notice: "Error"		
		end
	end

	def after_sign_in_path_for(resource)
  	dashboard_path
  end

	private
	def user_params
		devise_parameter_sanitizer.sanitize(:account_update).reject {|k,v| v.blank?}
	end
end

app/controllers/session/registrations_controller.rb
class Session::RegistrationsController < Devise::RegistrationsController


	def update
		@user = User.find(current_user.id)
		params[:user].delete(:current_password)
		if current_user.update_attributes(user_params)
			redirect_to dashboard_path, notice: "Successfully updated"
		else
			redirect_to dashboard_path, notice: "Error"		
		end
	end

	def after_sign_in_path_for(resource)
  	dashboard_path
  end

  def after_sign_out_path_for(resource)
  	super
  end

	private
	def user_params
		devise_parameter_sanitizer.sanitize(:account_update).reject {|k,v| v.blank?}
	end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController

	def create
		@subscribe = Subscribe.new(subscribe_params)
		if @subscribe.save
			redirect_to root_path, notice: "Prijava je uspesno poslata. Hvala na interesovanju ."
		else
			redirect_to root_path, notice: "Prijava nije uspesno prosla. Molimo pokusajte ponovo"
		end
	end

	private
	def subscribe_params
		params[:subscribe].permit(:email, :settlement_id)
	end
	
end

app/helpers/devise_helper.rb
module DeviseHelper
	
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new	
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end

end

app/helpers/flash_messages_helper.rb
module FlashMessagesHelper
  def flash_messages
    if flash[:alert]
      html = <<-HTML
        <div class='alert alert-danger'>
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          #{flash[:alert]}
        </div>
      HTML
      html.html_safe
    elsif flash[:notice]
      html = <<-HTML
        <div class='alert alert-success'>
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          #{flash[:notice]}
        </div>
      HTML
      html.html_safe
    end
  end
end

app/views/adverts/_form.html.haml
= form_for(@advert) do |f|
  - if @advert.errors.any?
    #error_explanation
      %h2
        = pluralize(@advert.errors.count, "error")
        prohibited this advert from being saved:
      %ul
        - @advert.errors.full_messages.each do |msg|
          %li= msg
  .actions
    = f.submit

app/views/adverts/edit.html.haml
%h1 Editing advert
= render 'form'
= link_to 'Show', @advert
|
\#{link_to 'Back', adverts_path}

app/views/adverts/index.html.haml
%button.btn.btn-default.pull-right{"data-toggle" => "modal", href: "#subscribe", id:"newsletter-subscribe"}
	Prijava za obavestenja
.container
	.jumbotron
		%center
			%h1
				DOBRODOSLI NA HAPPYHOUR.COM
				%p
					OVDE SE NALAZE NAJEFTINIJA MESTA ZA IZLAZAK
			%h4
				Mi se trudimo da ucinimo vas zivot jos jeftinijim
	.row.col-lg-12
		.panel.panel-default
			.panel-body
				This is where search criteria goes
	.container#adverts
		- @adverts.each do |advert|
			.col-lg-4
				.panel.panel-default
					.panel-body
						.panel-header
							%h3
								%center 
									= advert.title
						%h4
							= advert.description.truncate 25
							/TODO Postaviti Profil sliku za oglas
						.panel-side.pull-right
							%h5
								Kontakt:
								= advert.phone_number
							%h5
								Lokacija:
								= advert.location
							%h5
								Adresa:
								= advert.address
							%h6
								= link_to "Pogledaj detaljnije..", advert, id: "detaljnije-#{advert.id}"
= render 'shared/modals/subscribe_popup'
 

app/views/adverts/new.html.haml
%h1 New advert
= render 'form'
= link_to 'Back', adverts_path

app/views/adverts/show.html.haml
.container
	.jumbotron
		%center
			%h1
				= @advert.title
			%h3#advert-description
				= @advert.description
			/ TODO MAIN IMAGE
			/  GALERY
		.panel-side.pull-right
			%h5
				Kontakt:
				= @advert.phone_number
			%h5
				Lokacija:
				= @advert.location
			%h5
				Adresa:
				= @advert.address
	.panel-panel-default#table-comments
		.panel-heading
			%h2
				Komentari :
		- unless @advert.commentable
			Komentari nisu prikazani za ovaj oglas
		- else		
			= render @comments
			= render "comments/new"

app/views/comments/_comment.html.haml
.comment-panel
	%h3.panel-title
		= comment.owner
		at
		= comment.created_at
	.panel-body
		= comment.content

app/views/comments/_new.html.haml
.new-comment-form
	Ostavite svoj komentar :
	= simple_form_for [@advert, Comment.new] do |f|
		= f.input :owner, label: "Your name :"
		= f.text_field :content, row: 4, label: "Comment :"
		= f.submit "Post Comment"

app/views/dashboards/_user_dashboard.html.haml
/ %h3
/ 	= link_to "Back to home", root_path
/ %h3
/ 	%center
/ 		This is your dashboard
/ .bs-example
/ 	%ul.nav.nav-tabs
/ 		%li.active
/ 			= link_to "Profile", "#profile", :data => {:toggle => 'tab'}
/ 		%li
/ 			= link_to "Add new advert", "#new_advert", :data => {:toggle => 'tab'}
/ 		%li
/ 			= link_to "All my adverts", "#adverts", :data => {:toggle => 'tab'}
/ 	.tab-content
/ 		#profile.tab-pane.fade.in.active
/ 			%h3
/ 				This is your profile
/ 			%p
/ 				Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth.
/ 		#new_advert.tab-pane.fade
/ 			%h3
/ 				Add new advert
/ 		#adverts.tab-pane-fade
/ 			%h3
/ 				All my adds

app/views/dashboards/index.html.haml
/= render 'user/welcome_user_box'
.dashboard
  %h3
    = link_to "Back to home", root_path
  %h3
    %center
      Welcome to your dashboard ....
  .dashboard-panel
    %ul.nav.nav-pills
      %li.active
        = link_to "Profile", "#profile", :data => {:toggle => 'tab'}
      %li
        = link_to "Add new advert", "#new_advert", :data => {:toggle => 'tab'}
      %li
        = link_to "All my adverts", "#all_adverts", :data => {:toggle => 'tab'}
    %p
    .tab-content
      #profile.tab-pane.fade.in.active
        = render 'shared/edit_profile'
      #new_advert.tab-pane.fade
        = simple_form_for Advert.new do |f|
          .form-group
            = f.label "Naslov", class: "control-label col-xs-2", required: true
            .col-xs-10
              = f.input :title, required: true, label: false
          .form-group
            = f.label "Opis", class: "control-label col-xs-2", required: true
            .col-xs-10  
              = f.input :description, as: :text, row: 10, label: false
          .form-group
            = f.label "Kategorija", class: "control-label col-xs-2", required: true
            .col-xs-10 
              = f.association :category, label: false
          .form-group
            = f.label "Nacin placanja", class: "control-label col-xs-2"
            .col-xs-10
              = f.input :payment_method, as: :check_boxes, collection: Advert::PAYMENT.map{|m| [m[:name],m[:id]]}, label: false
          .form-group
            = f.label "Dozvoli komenare", class: "control-label col-xs-2"
            .col-xs-10
              = f.input :commentable, as: :boolean, label: false
          .form-group
            = f.label "Adresa lokala", class: "control-label col-xs-2", required: true
            .col-xs-10
              = f.input :address, label: false
          .form-group
            = f.label "Lokacija", class: "control-label col-xs-2", required: true
            .col-xs-10
              = f.input :location, label: false
          .form-group
            = f.label "Kontakt telefon", class: "control-label col-xs-2"
            .col-xs-10
              = f.input :phone_number, label: false
          .form-group
            .col-xs-offset-2.col-xs-10
              = f.submit "Postavi oglas"
      #all_adverts.tab-pane.fade
        - if @all_my_adverts.blank?
          %h3
            Niste postavili nijedan oglas 
        - else
          .container#my-adverts
            - @all_my_adverts.each do |advert|
              .col-lg-12
                .panel.panel-default
                  .panel-body
                    .panel-header
                      %h3
                        %left 
                          = advert.title
                    .panel-content
                      %h4
                        = advert.description
                      /TODO Postaviti Profil sliku za oglas
                    
                    .btn-group.pull-right
                      %button.btn.btn-default.btn-small{:disabled => "disabled", :type => "button"} 
                        = advert.created_at.to_date 
                      = link_to "Pogledaj detaljnije", advert, id: "detaljnije-#{advert.id}", class: 'btn btn-small btn-default'
= render 'shared/modals/preview_profile'

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title HappyHour
		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js?ver=1.4.0"></script> 
		= csrf_meta_tags
	- body_class = params[:controller].singularize
	%body{class: body_class}
		= render 'shared/header'
		= flash_messages
		= yield
		= render 'shared/footer'

app/views/shared/_edit_profile.html.haml
%h2
= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f|
  = f.error_notification
  .form-group
    = f.label "Email", class: "control-label col-xs-2" 
    .col-xs-10
      = f.input :email, :required => false, placeholder: current_user.email, label: false
  .form-group  
    = f.label "Nick", class: "control-label col-xs-2"
    .col-xs-10
      = f.input :user_name, :required => false, placeholder: current_user.user_name, label: false
  .form-group  
    = f.label "Ime", class: "control-label col-xs-2"
    .col-xs-10
      = f.input :first_name, :required => false, placeholder: current_user.first_name, label: false
  .form-group  
    = f.label "Prezime", class: "control-label col-xs-2"
    .col-xs-10  
      = f.input :last_name, :required => false, placeholder: current_user.last_name, label: false
  .form-group  
    = f.label "Mobilni 1", class: "control-label col-xs-2"
    .col-xs-10
      = f.input :mobile_number_1, :required => false, placeholder: current_user.mobile_number_1, label: false
  .form-group  
    = f.label "Mobilni 2", class: "control-label col-xs-2"
    .col-xs-10
      = f.input :mobile_number_2, :required => false, placeholder: current_user.mobile_number_2, label: false 
  .form-group
    = f.label "Avatar", class: "control-label col-xs-2"
    .col-xs-10
      = image_tag current_user.image_url(:thumb), class: "img-thumbnail" if current_user.image?
      = f.input_field :image      
  .form-group
    .col-xs-offset-2.col-xs-10
      = f.button :submit, "Save Changes", class: "btn btn-primary"
.form-group
  .col-xs-offset-2.col-xs-13
    %button.btn.btn-default{"data-toggle" => "modal", href: "#previewProfile"} Preview
/ %h3 Cancel my account
/ %p
/   Unhappy? #{link_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete}

app/views/shared/_footer.html.haml
.navbar.navbar-default.footer
	.container
		.navbar-text.pull-right
			Developed by 
			%em
				MI

app/views/shared/_header.html.haml
.navbar.navbar-inverse.navbar-static-top
  .container
    .navbar-brand
      = link_to  "Happy Hour", root_path
    %button.navbar-toggle{"data-target" => ".navHeaderCollapse", "data-toggle" => "collapse"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .collapse.navbar-collapse.navHeaderCollapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = user_signed_in? ? (render "user/welcome_user_box") : (render "shared/new_session")

app/views/shared/_new_session.html.haml
= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), html: { id: 'login-form', class: 'form-inline' }) do |f|
  .form-group
    = f.label "Email", class: "control-label col-xs-2" 
    .col-xs-10
      = f.input :email, label: false, class: 'form-control', placeholder: "Email", :autofocus => true
  .form-group
    = f.label "Sifra", class: "control-label col-xs-2" 
    .col-xs-10
      = f.input :password, label: false, class: 'form-control', placeholder: "Sifra"
  / .form-group
  /   = f.label "Zapamti me",class: "control-label col-xs-2"   
  /   .col-xs-10
  /     = f.input :remember_me, :as => :boolean, label: false if devise_mapping.rememberable?
  .form-group
    .col-s-offset-5.col-s-10
      = f.button :submit, "Prijavi se", class: "btn btn-default"

app/views/shared/modals/_preview_profile.html.haml
#previewProfile.modal.fade
	.modal-dialog
		.modal-content
			.preview-profile
				#avatar
					= image_tag current_user.image_url(:thumb), class: "img-thumbnail" if current_user.image?
				.modal-body
					.modal-preview-profile
						.row 
							.col-sm-4
								%h5 Ime:
								= current_user.first_name
							.col-sm-4
								%h5 Prezime:
								= current_user.last_name
							.col-sm-4
								%h5 Nick
								= current_user.user_name
						.row
							.col-sm-4
								%h5 Email:
								= current_user.email
							.col-sm-4
								%h5 Mobilni 1
								= current_user.mobile_number_1
							.col-sm-4
								%h5 Mobilni 2
								= current_user.mobile_number_2

app/views/shared/modals/_subscribe_popup.html.haml
#subscribe.modal.fade
	.modal-dialog
		.modal-content
			.modal-header#subscribe-header
				Prijava za obavestenja
				#subscribe-description
					Izaberite opstinu za koju zelite da vam stizu obavestenja jednom nedeljno
			.modal-body
				.subscribe-form
					= form_for Subscribe.new , html: {class: "form-inline"} do |f|
						= f.label "Email"
						.form-group
							= f.text_field :email, type: "email", class: "form-control", id: "inputEmail"
						= f.label "Opstina"
						.form-group
							= f.select :settlement_id, @settlements.map{|m| [m[:name],m[:id]]}, prompt: "Sve opstine", class: "form-control", id: "selectSettlement"
						.form-group
							= submit_tag "Posalji prijavu", class: "btn btn-default"

app/views/user/_welcome_user_box.html.haml
%ul.nav
  %li.dropdown
    %a.dropdown-toggle{:href => "#", "role" => "button", "data-toggle" => "dropdown", "data-target" => "#"} 
      Welcome,
      = current_user.user_name
      %b.caret
    %ul.dropdown-menu{"role" => "menu"}
      %li
        %a{:href => dashboard_path} 
          My dashboard
        %a{:href => "#link2"} 
          My profile
        %a{:href => destroy_user_session_path, :method => :delete } 
          Sign out